#!/bin/bash

PARENT_PROCESS=$(ps -o comm= $PPID) 
DOCKER_CMD=$1
DOCKER_CONTAINER=$2

COMMANDS=("pull" "up" "start" "stop" "rm" "clean" "exec COMMAND [ARGS]" "logs" "ps" "cp FILE CONTAINER_DIRECTORY")

function usage() {
   printf '%s\n\t' "Usage: $0 " "${COMMANDS[@]}"
}

case $DOCKER_CMD in
  pull)
    ./docker-utils pull $DOCKER_CONTAINER
    ;;
  up)
    ./docker-utils up $DOCKER_CONTAINER
    ;;
  start)
    ./docker-utils start $DOCKER_CONTAINER
    ;;
  stop)
    ./docker-utils stop $DOCKER_CONTAINER
    ;;
  rm)
    ./docker-utils rm $DOCKER_CONTAINER
    ;;
  clean)
    ./docker-utils clean $DOCKER_CONTAINER
    ;;
  exec)
    CONTAINER_CMD=$3
    ARGUMENTS=($@)
    ARGUMENTS=(${ARGUMENTS[@]:3})
    
    if [ ! -z "$ARGUMENTS" ]; then
      ./docker-utils exec $DOCKER_CONTAINER $CONTAINER_CMD ${ARGUMENTS[@]}
    else
      ./docker-utils exec $DOCKER_CONTAINER $CONTAINER_CMD
    fi
    ;;
  logs)
    ./docker-utils logs $DOCKER_CONTAINER
    ;;
  ps)
    ./docker-utils ps $DOCKER_CONTAINER
    ;;
  cp)
    FILE=$3
    CONTAINER_DIRECTORY=$4
    
    ./docker-utils cp $DOCKER_CONTAINER $FILE $CONTAINER_DIRECTORY
    ;;
  *)
    if [[ $PARENT_PROCESS =~ ((^(bash|fish)$)) ]]; then
      ./docker-utils usage
    else
      usage
    fi
    exit 1
esac
