#!/bin/bash

EXECUTION_PATH=$(cd `dirname $0` && pwd)
IMAGE_EXT=$1
IMAGE_DIRECTORY=$2
INPUT_TRAY="/opt/jboss/welcome-content/input-tray"

if [ -z "$IMAGE_EXT" ]; then
  IMAGE_EXT="png"
fi

if [ -z "$DOCKER_CONTAINER" ]; then
  DOCKER_CONTAINER="app"
fi

if [ -z "$IMAGE_DIRECTORY" ]; then
  IMAGE_DIRECTORY="~/Resources/images"
fi

IMAGES=$(eval "ls $IMAGE_DIRECTORY/*.$IMAGE_EXT")
IMAGE=${IMAGES[$((RANDOM % ${#IMAGES[@]}))]}

echo "Coping $IMAGE to $DOCKER_CONTAINER:$INPUT_TRAY ..."
$EXECUTION_PATH/wildfly-server set $IMAGE $INPUT_TRAY

FILE_END="$(echo $IMAGE | rev | cut -d'/' -f1 | rev)"
IMAGE_EXT_LEN=$(echo -n $IMAGE_EXT | wc -c)
FILE_END="${FILE_END::-$IMAGE_EXT_LEN}end"

echo "Creating the .end file $FILE_END on $INPUT_TRAY ..."
$EXECUTION_PATH/wildfly-server exec bash "cd $INPUT_TRAY; touch $FILE_END" 

