#!/bin/bash

EXECUTION_PATH=$(cd `dirname $0` && pwd)

OPTS=`getopt -o h --long help -- "$@"`
eval set -- "$OPTS"

#GENERIC_COMMANDS

function usage() {
  printf '%s\n\t' "Usage: $0" "${GENERIC_COMMANDS[@]}"
}

while true
  do
    case "$1" in
      -h | --help)
        usage; exit 0 ;;
      --)
        shift; break ;;
      *)
        shift; break ;;
    esac
  done

DOCKER_ARGS=$@

cd $EXECUTION_PATH/..
bash bin/main $DOCKER_ARGS --script-type generic
